name: Brokerage Admin CI/CD

on:
  push:
    branches: 
      - test

jobs:
  build_admin:
    runs-on: ubuntu-latest
    steps: 

      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Node
        uses: actions/setup-node@v2
        with:
            node-version: '18'

      - name: Install module
        run: npm install --force
        working-directory: admin

      - name: Build project
        run: npm run build
        working-directory: admin

      - name: Configure SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: '-----BEGIN OPENSSH PRIVATE KEY-----
b3BlbnNzaC1rZXktdjEAAAAACmFlczI1Ni1jdHIAAAAGYmNyeXB0AAAAGAAAABDJQCn36o
KGQZltFY0V+zTGAAAAGAAAAAEAAAGXAAAAB3NzaC1yc2EAAAADAQABAAABgQCgl71/1krm
WTothhhPxNnDIE+EclFjA51OJsLcOOwsWvkTs1e1qa2bzb6U9ixtU9XpGBLv19k2cWupIv
fgye9IXTeWP3tey/l4Q5oshU0dH7h+/2c4zntuvuPbxCqaPA6nBWax1bVGeDrw15JRJcnW
IkmpvyqsFX8eqB4bHXT1Ew2M8m2kHf6y4yjKXVnqXJQKk2g8f90aMBHU3Y+X4PesEbasI9
qaFUjXl3Fsisja5L+6Fhbn4mraiz6Ad1386QWkQgieCIyPF2VAiopI8hhhUiH3YeYRAJx4
WV+hkEJmdcXKK7cLfEYWR1V6vhNy3rGyTFrlFUmejcp5r+TgJ8q55tS6mCmFqdUFlaD/Iq
fICnK8PoJGz9rHfDVzoWo5Had0egvN71GLHqHNcM6yq8ru4H+Diz3UWVqDOH7tts7hfCgF
NoTy7EU5DzEUBevqgnKtfNdf54XGWOt1J/C7QNKyAD64nduFKw6TQfTAkfEIxoxVrVvIZY
EqwZyjfF5rwFMAAAWQV9zbJM/h2jsDY4HA3TapY6kQ1j4M4cN4JiDTP3YRR5mVkBSbf0Yi
iT8eATJI0pQNXeLHCiL/wdGh9K81PPkT3yPaRU8zMirZ2OZg9VzuQUSfLosjDSFElD6qOP
F+miKjnvJUtqs6d21PlhrfAHWqEtcGGz1RBNMzrsVBzYoGu88nAo6SU8SL2A9JH8BNEzJJ
sG+7zkLfM2JATx4sWKusZTHJvaEL/g52E2YnWT1CpkCoVXoJAeE6CpI+noDYCv/wvyE606
4j2sUmknZ+80YSCR4supyUgVcg+gDQfKQ3gICDcTDImie6EncmnNcY3lQ1Fbx+i4vIHmKZ
viGy2unrB5+hxXf7C+nBJcLAO5kWizbveFSRR2ZlM1ZNdRHShzRppPqT+3GP1/jgWDP+5W
bqamzvosL7IMEx3tfG+OBTCjbqmTnrHalKmdme2yGoaEQ1U7kYXnkCRUhuhr916Ks4cJM+
VvZQR7kJW9Xz76IKlA0CvbM8sbaNBhFU7R4hNDuOKxUdtFV8zqfnb1AJVaWDwdnCKPcxa0
H8zxeh8Rr3dZUHvp+r1+CEidCkM5sYCPYTvN1i68tBkGnyPRzBCeuZ9j3LrRqC9IQ+dN8u
gTBdAQ1AffRBnZrxYya6ATRsKgXXI01wAn41mq14JvTrhWajGA8jHNQEdTvXsMYt8NOItR
F7KnxI0JTwFJAKg0qXCVCcSu01jHYUBxASvUquPOiA1cuGqc6msPTfcWzrIHW9R2DarAA2
raSP6InO8qzSh/76zPw6Nya7UBHYeCIrZlenvtsEkpJ2+GEgE9uAbYYvA3MvlTfpxBzfod
VE2hWnWvmNSjXmlg7qPaVnVw/SSxeTvGtYueQBk6OXpj9BrTmgwASsPegEpyxekQJRzh/D
q1YSMy44Zw+XpuldJ6gwTiLsgDkcAsRH8g3no0D1c9lgzqT/tsr18CS2Bl+vCsegNY4T7B
IQjKwPnRomtWjRYY1XI95MN15xppH6KkDqN+ztxtrd02yifV83Z0+YGKp+06ALsJLNg0u2
LR9gc9uBJB/dcWuHfFpA9StxyF2WnjPtSO0/Ejkmu1Q+HObwzdpyx9Ogd0jk2kTJ0JDXwP
h5afOIWgyeVcCtf995+J4KFg1AXlF24k9qYmUEXDI9mr1m7mS67gdgBvswUUKKvQU7/xTd
gubBNDZSrhdrF4OmhxGEShemY9sQxXZir6wDczWD6aFe9ZlqJMi9mhVxaSuwhopFVVfEIO
O4xzwfShCFixCx0SrhHP5IC+Qlcr0xgTSRynjKMVIn+TOOUFn+zSpAvIxDtAqGAlORQJIv
oyrmbi3Hh1wV5A4jOgiHZeD9GEPgWCZsp/hnFKwJkvC3Y1L6wqR4ZBiMcvOHeQ4F+8I9NK
BVxT1KpoCbcBt66FqZMUKtRjNvPeuyGXc9IVv79m5hS9J/xnlYYpNGm2loG7ofN8rW6aFs
0mVnsrItQquAHnqxfqee7vQAPAEIVUm5CuP03lW5xuxjGTE0keQd3yX1GiBVf1o/De/Bxm
kBIK0mZ41pMmTo0DRj5GQSv3h4uXBv2UZO3aCpUS/GS8M+QsYDLl/O6M+1P5iq5F7cyfi6
wGwzMmupG0mjjFF9t0PgOmjrfGOtDa8W0YcLBuG1INst4k5fvdFTD5+dow+z8S3fZZ5U1t
PIYF8sthJqU5LgI0bX+EsnChr5HBZsh3bu4WA0FGi9Dqq10Ohizv1VvuA5CvxppyXSfM59
D6LA3tWaXeBJPAjksQlJqJBDun+HhTMUokG31iUwbAeQO6TOk3s0C/80R+TxFuxhFRePJA
Z1xpiiypKaq7Q8HOuI+vHLcAi27rg3xSeR7z1mmsNx8i20tFRdo8J4EfGPHImOpZ2p8+E7
O4ef8X7t0vdQH50HoVtxQvys8SQ=
-----END OPENSSH PRIVATE KEY-----'

      - name: Change owner of directory
        run: ssh -o StrictHostKeyChecking=no root@77.37.86.28 'sudo chown -R root:root ../home/projects/brokerage-admin/build'
      
      - name: Deploy with rsync
        run: rsync -e 'ssh -o StrictHostKeyChecking=no' -r /home/runner/work/bbscrm/bbscrm/admin/build root@77.37.86.28:../home/projects/brokerage-admin/build
